/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e2199c88-b998-455a-ab26-3df9cf34ee07",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8lnva5DaB",
    "aws_user_pools_web_client_id": "6htlo339atsaak7jpl4pfi9m35",
    "oauth": {}
};


export default awsmobile;
